server:
  port: 9082
dubbo:
  application:
    name: register-service
  registry:
    address: zookeeper://192.168.2.131:2181
  protocol:
    port: 20882
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qf-yl?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "0220"
  rabbitmq:
    host: 192.168.2.142
    username: rabbit
    password: 123456
    port: 5672
  redis:
    host: 192.168.2.137
    port: 6379
    password: 123
    jedis:
      pool:
        max-active: 60
