server:
  port: 9084
dubbo:
  application:
    name: product-type-service
  registry:
    address: zookeeper://192.168.2.131:2181
  protocol:
    port: 20884
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qf-yl?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "0220"
