itemServices:
  path: /usr/local/docker/nginx/wwwroot/htmlservice/
server:
  port: 9086
dubbo:
  application:
    name: product-info-service
  registry:
    address: zookeeper://192.168.2.131:2181
  protocol:
    port: 20886

spring:
  datasource:
    url: jdbc:mysql://192.168.2.170:3306/qf-yl?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "0220"
  rabbitmq:
    host: 192.168.2.142
    username: rabbit
    password: 123456
    port: 5672
