server:
  port: 9089
dubbo:
  application:
    name: sms-service
  registry:
    address: zookeeper://192.168.2.131:2181
  protocol:
    port: 20889

spring:
  redis:
    host: 192.168.2.137
    port: 6379
    password: 123
    jedis:
      pool:
        max-active: 60
#  datasource:
#    url: jdbc:mysql://localhost:3306/qf-yl?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: "0220"
#  rabbitmq:
#    host: 192.168.2.142
#    username: rabbit
#    password: 123456
#    port: 5672
#  mail:
#    host: smtp.qq.com
#    username: 2469193981@qq.com
#    password: pezpizfcirpcdibc
#    default-encoding: utf-8


