server:
  port: 9087
dubbo:
  application:
    name: shopping-cart-service
  registry:
    address: zookeeper://192.168.2.131:2181
  protocol:
    port: 20887

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qf-yl?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "0220"
  redis:
    host: 192.168.2.137
    port: 6379
    password: 123
    jedis:
      pool:
        max-active: 60

