server:
  port: 8094
dubbo:
  application:
    name: product-manage-web
  registry:
    address: zookeeper://192.168.2.131:2181
spring:
  thymeleaf:
    cache: false
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.2.133:22122

image:
  server: 192.168.2.133:8888
